name: Deploy

on:
  push:
    branches: ["main", "dev"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast1
  REPO_NAME: docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "SERVICE_NAME=agentic-tuya-smart-api" >> $GITHUB_ENV
            echo "IMAGE_NAME=agentic-tuya-smart-api" >> $GITHUB_ENV
          else
            echo "SERVICE_NAME=agentic-tuya-smart-api-dev" >> $GITHUB_ENV
            echo "IMAGE_NAME=agentic-tuya-smart-api-dev" >> $GITHUB_ENV
          fi

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_URL=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build --platform linux/amd64 -t $IMAGE_URL .
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: "--allow-unauthenticated --memory=128Mi --cpu=1 --min-instances=0 --max-instances=1 --cpu-boost"
          env_vars: |
            APP_ENV=${{ vars.APP_ENV }}
            TUYA_BASE_URL=https://openapi.tuyaus.com
            PORT="8080"
            TUYA_ACCESS_ID=${{ secrets.TUYA_ACCESS_ID }}
            TUYA_ACCESS_SECRET=${{ secrets.TUYA_ACCESS_SECRET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          secrets: |
            API_KEY=API_KEY:latest

      - name: Make Service Public
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --member="allUsers" \
            --role="roles/run.invoker"
